# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a93526306168e90480fc9c0f69e7fc0fea3baf59f3379852e9d815cd315426521488333e47d7c375f7b6cc0d387ae7a240859cf633b2bc50b40a91d6ed336ed9

test:
  secret_key_base: d94b60737640d0fe037628e8718dd8c90f7ecddb132d177f0b66eca5987e785a07f4030c14e3c3aee4490df29a96e0b18c1d60f4df70e5fdb667f780ace5d7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
